### ISSUE TITLE
Page Creation Ends In Error

### ISSUE THREAD

**Issue by dennismensah** [jonataslaw/get_cli#26] opened 2020-10-14 17:02 UTC
when i enter the page creation command it ends in an error which closes the terminal. The folder is created though.

**Comment by jonataslaw** [comment] 2020-10-15 15:03
What SO do you use?
What version from get_cli?

**Comment by dennismensah** [comment] 2020-10-15 15:31
I'm on get cli version 1.3.12 and flutter 1.22

**Comment by dennismensah** [comment] 2020-10-15 15:50
I'm on windows

**Comment by jonataslaw** [comment] 2020-10-15 15:53
duplicate of https://github.com/jonataslaw/get_cli/issues/24

**Closed by jonataslaw** 2020-10-15 15:53 UTC
